#data
dataset_name: license_plates
train_data_path: data/license_plates_synth/train
val_data_path: data/license_plates_synth/val
batch_size: 48
resume: #filepath do postojeceg modela pokazuje tocno na model.pth file npr /checkpoints/model.pth
random_color_flag: True   # True: generate random corruption | False: sample from mask_colors
mask_colors:
  - [0, 0, 0]
  - [255, 255, 255]
epoch_visualization_timing: end   # start | end | both | none

#training
device: cuda
num_workers: 4
lr: 0.0001
epochs: 100
stopping_patience: 20

#model
encoder_name: resnet34
encoder_weights: imagenet
in_channels: 4
num_classes: 3
